export const FETCH_STUDENTS_REQ = 'FETCH_STUDENTS_REQ';
export const FETCH_STUDENTS_RES = 'FETCH_STUDENTS_RES';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const REG_STUDENT_REQ = 'REG_STUDENT_REQ'
export const REG_STUDENT_RESET = 'REG_STUDENT_RESET'
export const REG_STUDENT_RES = 'REG_STUDENT_RES'
export const REG_STUDENT_FAIL = 'REG_STUDENT_FAIL'
export const DELETE_STUDENT_REQ = 'REG_STUDENT_REQ'
export const DELETE_STUDENT_RES = 'REG_STUDENT_RES'
export const DELETE_STUDENT_FAIL = 'REG_STUDENT_FAIL'

